disable IDE0031 // Use null propagation (IDE0031) Correction is called: Error CS0131: The Left-Hand Side of An Assignment Must Be a Variable, Property Or Indexer