[main] Update dependencies from dotnet/arcade (#10274)
* Update dependencies from https://github.com/dotnet/arcade build 20250703.1

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25353.1

* Use setup-dotnet task with global.json

* Update dependencies from https://github.com/dotnet/arcade build 20250708.3

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25358.3

* Update dependencies from https://github.com/dotnet/arcade build 20250717.3

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25367.3

* Update dependencies from https://github.com/dotnet/arcade build 20250717.5

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25367.5

* Update dependencies from https://github.com/dotnet/arcade build 20250724.4

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25374.4

* Update dependencies from https://github.com/dotnet/arcade build 20250801.2

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25401.2

* Update dependencies from https://github.com/dotnet/arcade build 20250808.3

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25408.3

* Update dependencies from https://github.com/dotnet/arcade build 20250815.5

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25415.5

* Update dependencies from https://github.com/dotnet/arcade build 20250819.2

Microsoft.DotNet.Arcade.Sdk , Microsoft.DotNet.Build.Tasks.Archives , Microsoft.DotNet.Helix.Sdk , Microsoft.DotNet.RemoteExecutor , Microsoft.DotNet.SharedFramework.Sdk , Microsoft.DotNet.XliffTasks , Microsoft.DotNet.XUnitV3Extensions
 From Version 10.0.0-beta.25351.1 -> To Version 10.0.0-beta.25419.2

* Use restored dotnet for running tests out of repo

* Update nuget.config used for template testing to include dotnet10 feed

* add dotnet10 to nugetconfig

* Revert "Use restored dotnet for running tests out of repo"

This reverts commit 5143d6b6fc985d93eff3fe7f09eb35232ec23096.

* show dotnet-info

* Upload crash dumps in a separate artifact

* fix yml

* Fix EndToEnd tests

`setup-dotnet` is installing only 8.0 and 10.x even though global.json
lists a 9.0 version too. List the versions explicitly instead.

```
    ----- Inner Stack Trace -----
    at Aspire.Templates.Tests.AspireProject.StartAppHostAsync(String[] extraArgs, Action`1 configureProcess, Boolean noBuild, Boolean waitForDashboardUrl, CancellationToken token) in /_/tests/Shared/TemplatesTesting/AspireProject.cs:317
    at Aspire.EndToEnd.Tests.IntegrationServicesFixture.InitializeAsync() in /_/tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs:83
failed Aspire.EndToEnd.Tests.IntegrationServicesTests.VerifyHealthyOnIntegrationServiceA (0ms)
  Xunit.Runner.InProc.SystemConsole.TestingPlatform.XunitException: Class fixture type 'Aspire.EndToEnd.Tests.IntegrationServicesFixture' threw in InitializeAsync
  ---- System.InvalidOperationException : App exited before startup could complete with exit code 150. It ran for 00:00:00.7418015 secs.:
  [apphost] You must install or update .NET to run this application.
  [apphost]
  [apphost] App: /home/runner/work/aspire/aspire/run-tests/testassets/testproject/TestProject.AppHost/bin/Debug/net8.0/TestProject.AppHost
  [apphost] Architecture: x64
  [apphost] Framework: 'Microsoft.AspNetCore.App', version '8.0.0' (x64)
  [apphost] .NET location: /usr/share/dotnet
  [apphost]
  [apphost] The following frameworks were found:
  [apphost]   10.0.0-preview.7.25372.107 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  [apphost]
  [apphost] Learn more:
  [apphost] https://aka.ms/dotnet/app-launch-failed
  [apphost]
  [apphost] To install missing framework, download:
  [apphost] https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0&arch=x64&rid=linux-x64&os=ubuntu.24.04
```

---------

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Ankit Jain <radical@gmail.com>