Fix xunit template build
```
... testroot/aspire-aspire-xunit/aspire-aspire-xunit.aspire-xunitTests/IntegrationTest1.cs(21,27): error CS1061:
'IServiceCollection' does not contain a definition for 'ConfigureHttpClientDefaults' and no accessible extension method 'ConfigureHttpClientDefaults' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [/datadisks/disk1/work/B74F0975/t/testroot/aspire-aspire-xunit/aspire-aspire-xunit.aspire-xunitTests/aspire-aspire-xunit.aspire-xunitTests.csproj]
```